workflow:
  start-at: segmentation
  stop-at: segmentation
  segmentation-channel: 1 1

options:
  unmicst: --tool unmicst-duo --scalingFactor 0.4 --outlier 99.9
  s3seg: --maxima-footprint-size 13 --area-max 50000 --expand-size 5 --pixelSize 0.325 --mean-intensity-min 128

modules:
  watershed:
    name: s3seg
    container: labsyspharm/s3segmenter
    version: 1.5.6-large